version: "2"

checks:
    file-lines:
        enabled: true
        config:
            threshold: 500  # 1000 is really the hard edge

    method-lines:
        enabled: true
        config:
            threshold: 25

    method-complexity:
        enabled: true
        config:
            threshold: 8

    #argument-count:
        #enabled: true
        #config:
            #threshold: 5  # add 1 for `self` in Python

plugins:
    radon:
        enabled: true
        config:
            threshold: "C"

    fixme:
        enabled: true
        config:
            strings:
                - FIXME
                - BUG
                - TODO
        issue_override:
            severity: info

    duplication:
        enabled: true
        checks:
            Similar code:
                enabled: true
                issue_override:
                    severity: info
        config:
            languages:
                python:
                    mass_threshold: 35

exclude_patterns:
    - "docs/"
    - "tests/"
    - "cover/"
    - "version.py"
